name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Launch shell from the development container
      run: ./tools/dev_container --clean
    - name: Build
      run:  cargo build --features "virgl_renderer,video-encoder,video-decoder,ffmpeg"
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.4.3
      with:
        path: /scratch/cargo_target/debug/crosvm
        if-no-files-found: error
        overwrite: true
