name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      CROSVM_CACHE_DIR: /home/runner/work/crosvm/cache

    steps:
    - name: Setup
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build
      run: ./tools/dev_container --clean /bin/bash -c "cargo build --features \"virgl_renderer,video-encoder,video-decoder,ffmpeg\"; cp -r /scratch/cargo_target/debug/crosvm /cache/artifacts"
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.4.3
      with:
        path: /home/runner/work/crosvm/cache/artifacts
        if-no-files-found: error
        overwrite: true
